FROM python:3.7-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY . /code/
RUN pip3 install dash django django-plotly-dash xlrd==1.2.0 bootstrap4 dash-bootstrap-components pandas numpy scikit-learn django-bootstrap4 dpd-static-support